apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-random-app
spec:
  selector:
    matchLabels:
      app: new-random-app
  replicas: 2
  template:
    metadata:
      labels:
        app: new-random-app
    spec:
      containers:
      - name: new-random-app
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
