apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-random-app
spec:
  selector:
    matchLabels:
      app: new-random-app
  replicas: 4
  template:
    metadata:
      labels:
        app: new-random-app
    spec:
      containers:
      - name: new-random-app
        image: https://hub.docker.com/r/nanajanashia/argocd-app:1.0
        ports:
        - containerPort: 8080
